---
language: python
python: "2.7"

install:
  - pip install ansible

script:
  ansible-playbook --inventory localhost, --connection local --syntax-check playbook.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
