---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=1.9 NEXT_ANSIBLE_VERSION=2.0
  - ANSIBLE_VERSION=2.0 NEXT_ANSIBLE_VERSION=2.1
  - ANSIBLE_VERSION=2.1 NEXT_ANSIBLE_VERSION=2.2
  - ANSIBLE_VERSION=2.2 NEXT_ANSIBLE_VERSION=2.3
  - ANSIBLE_VERSION=2.3 NEXT_ANSIBLE_VERSION=2.4
  - ANSIBLE_VERSION=2.4 NEXT_ANSIBLE_VERSION=2.5

install:
  - pip install ansible>="$ANSIBLE_VERSION",<"$NEXT_ANSIBLE_VERSION"

branches:
  only:
    - master

script:
  ansible-playbook --inventory localhost, --connection local --syntax-check playbook.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
