---
# Setup/install tasks
- include: setup-RedHat.yml
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- include: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include: setup-Fedora.yml
  when: ansible_distribution == 'Fedora'

- include: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Configuration tasks
- name: link /etc/openresty to /etc/nginx
  file:
    state: link
    src: /etc/openresty
    path: /etc/nginx

- debug: var=ansible_service_mgr

- name: link openresty init script as nginx for service
  file:
    state: link
    src: /etc/init.d/openresty
    path: /etc/init.d/nginx

- name: create nginx service for systemd
  copy:
    src: etc/systemd/system/nginx.service
    dest: /etc/systemd/system/nginx.service
  when: ansible_service_mgr == 'systemd'

- name: create standard nginx directories
  file:
    state: directory
    path: /etc/nginx/{{ item }}
  with_items:
    - conf.d
    - sites-enabled
    - sites-available

- name: install default nginx configuration
  template:
    src: etc/nginx/{{ item }}.j2
    dest: /etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - conf.d/defaults
  notify: restart nginx
