---
- name: Enable OpenResty repo
  template:
    src: openresty.repo.fedora.j2
    dest: /etc/yum.repos.d/openresty.repo
    owner: root
    group: root
    mode: 0644

- name: Install OpenResty package
  yum:
    name: "openresty"
    state: installed
